### ISSUE TITLE
What are the models that needed in the TabCBM

### ISSUE THREAD

**Issue by aseslamian3** [mateoespinosa/tabcbm#1]
Hello!
I am trying to use TabCBM for my own tabular datasets which are provided in CSV file. In the model provided, it required some required models such as:
feature_to_concept_model
concept_to_feature_model

So, What does these parts means? It is not referred to it in the paper with details. For example, assume that we have tabular data for train with 1000 rows and 7 columns which are features and 1000 elements vector with binary elements. How can we use TabCBM to train a model for test data?

**Comment by mateoespinosa** [comment]
Hello!

Sincerest apologies for the massive delay. I've just gotten some cycles to return to this question + add some new bits to help clarify this library. To help with this, I have added a [new notebook](https://github.com/mateoespinosa/tabcbm/blob/main/examples/sim_nonlin_train_walkthrough.ipynb) showcasing how to use `TabCBM` in a custom dataset. Furthermore, please note that I just pushed a big library cleanup and an update of the `README` file to clarify each argument. Please refer to both of these files (the example and the README) as a reference for using this library.

To specifically answer your questions here:
1. `features_to_concepts_model` is the $\phi$ model used in the paper. Its job is to map input features to some latent code from which the concept generators operate.
2. There is no `concept_to_feature_model`, but I imagine you meant `concepts_to_labels_model`. If that is the case, then `concepts_to_labels_model` is the $f$ model used in the paper. Its job is to map a set of concept scores to a set of output label predictions.
3. I hope the new notebook example may clarify how to use it for a custom dataset! Please let me know if that is not the case.

I will close this ticket for now as I hope this answers your concerns. However, if things are still unclear and/or you run onto any further issues, please do let me know! Happy researching!
